config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :order_items
  resources :orders
  resources :assets
  resources :products
  resources :categories

  post "cart/add/:id" => 'cart#add', as: :buy
  get "cart/remove/:id" => 'cart#remove', as: :remove
  get "cart/destroy" => 'cart#destroy', as: :clear

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base
has_many :cart_items
has_many :products, :through => :cart_items

  def total_amount
    #  sum = 0
    # cart_items.each do |cart_item|
    #   sum += cart_item.price * cart_item.quantity
    # end
    #  sum
    cart_items.inject(0) { |sum, item| sum + item.total_price }
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
before_action :initialize_cart

def add
  @pruduct = Product.find(params[:id])
  @items = @cart.cart_items.where(:product_id => params[:id])

    if @items.size < 1
      ci = @cart.cart_items.create( :product_id => params[:id], :quantity => params[:quantity].to_i)
    else
      ci = @items.first
      ci.quantity = ci.quantity + params[:quantity].to_i
      ci.update_attribute(:quantity , ci.quantity)
    end
  ci
   redirect_to :back, notice: '商品已放入購物車 Items was successfully added.'
end


def remove
  ci = @cart.cart_items.where(:product_id == params[:id]).first

  if ci
    @cart.cart_items.delete(ci.id)
  end

  redirect_to :back, notice: '已移除商品 Items was successfully removed.'
end


def destroy
  @cart.cart_items.destroy_all
  redirect_to :back, notice: '已清空購物車 Items was successfully cleared.'
end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart.html.erb
<h3>Your shopping cart<span><p><%= link_to "清空購物車", clear_path  %></p></span></h3>

<% if @cart.cart_items.count > 0 %>
  <table class="table">

    <thead>
      <tr>
        <td>Image</td>
        <td>Name</td>
        <td>Price</td>
        <td>Quantity</td>
        <td>Total</td>
        <td></td>
      </tr>
    </thead>

    <tbody>
      <%= @cart.cart_items.each do |cart_item| %>
        <tr>
          <td><%= image_tag cart_item.product.image.thumb.url %></td>
          <td><%= cart_item.product.name %></td>
          <td><%= cart_item.product.price %></td>
          <td><%= cart_item.quantity %></td>
          <td><%= number_to_currency( cart_item.total_price ) %> </td>
          <td><%= link_to 'Delete', remove_path(:id => cart_item.product.id)  %></td>
        </tr>
      <% end %>
    </tbody>

  </table>


<tr>
  <td colspan="2">Total amount</td>
  <td><%= number_to_currency(@cart.total_amount) %></td>
</tr>
<% else %>
  <%= "You have no items in cart!" %>
<% end %>

<p><%= link_to '結帳去', new_order_path  %></p>

app/views/cart/checkout.html.erb
<h3>Checkout</h3><p><%= link_to "清空購物車", clear_path  %></p> <p><%= link_to '繼續購物', products_path %></p>

<h4>購物清單</h4>

 <table class="table">

    <thead>
      <tr>
        <td>Image</td>
        <td>Name</td>
        <td>Price</td>
        <td>Quantity</td>
        <td>Total</td>
        <td></td>
      </tr>
    </thead>

    <tbody>
      <%= @cart.cart_items.each do |cart_item| %>
        <tr>
          <td><%= image_tag cart_item.product.image.thumb.url %></td>
          <td><%= cart_item.product.name %></td>
          <td><%= cart_item.product.price %></td>
          <td><%= cart_item.quantity.to_i %></td>
          <td><%= cart_item.total_price %> </td>
          <td><%= link_to 'Delete', remove_path(:id => cart_item.product.id)  %></td>
        </tr>
      <% end %>
    </tbody>

  </table>
<p>Total amount : <%= @cart.total_amount %>  </p>