config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :order_items
  resources :orders
  resources :assets
  resources :products
  resources :categories

  post "cart/add/:id" => 'cart#add', as: :buy
  get "cart/remove/:id" => 'cart#remove', as: :remove
  get "cart/destroy" => 'cart#destroy', as: :clear

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                   :integer          not null, primary key
#  name                 :string
#  ship_to_address      :string
#  phone_number         :string
#  ship_to_name         :string
#  ship_to_phone_number :string
#  status               :string
#  customer_ip          :string
#  email                :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Order < ActiveRecord::Base
  has_many :order_items
  has_many :products, :through => :order_items

  validates_presence_of :name, :ship_to_address, :phone_number ,:ship_to_name ,:ship_to_phone_number

  STATUS = [
    ["New", :new],
    ["Done", :done]
  ]

  def total
    # order_items.inject(0) {|sum, n| n.price * n.quantity + sum}
    order_items.map(&:total).sum
  end


  def paypal_url(return_path)
        values = {
        business: "bomibar3-facilitator@gmail.com",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        invoice: id,
        amount: order_items.map(&:total).sum,
        # item_name: order_item.product.name,
        # item_number: order_item.product_id,
        quantity: '1'
    }
  "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :cart_is_not_empty, only: [:new]



  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new

  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.customer_ip = request.remote_ip

    add_cart_item_to_order

    # respond_to do |format|
      if @order.save
        @cart.cart_items.destroy_all
        redirect_to @order.paypal_url(order_path(@order))

        # format.html { redirect_to @order, notice: '訂單成立!' }
        # format.json { render :show, status: :created, location: @order }
      # else
        # format.html { render :new }
        # format.json { render json: @order.errors, status: :unprocessable_entity }
      # end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :ship_to_address, :phone_number, :ship_to_name, :ship_to_phone_number, :status, :customer_ip, :email)
    end


    def cart_is_not_empty
      if @cart.cart_items.count < 1
        redirect_to :back, notice: "Cart can not be empty @@"
      end
    end

    def add_cart_item_to_order
    @cart.cart_items.each do |item|
      order_item = OrderItem.new(
        :product_id => item.product_id,
        :price => item.product.price,
        :quantity => item.quantity
      )
      @order.order_items << order_item
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<hr>
<%= form_for(@order) do |f| %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%# if @order.errors[:name].present? %>
    <%#= @order.errors[:name].join(", ") %>
    <%# end %>
  </div>
  <div class="field">
    <%= f.label :ship_to_address %><br>
    <%= f.text_field :ship_to_address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :ship_to_name %><br>
    <%= f.text_field :ship_to_name %>
  </div>
  <div class="field">
    <%= f.label :ship_to_phone_number %><br>
    <%= f.text_field :ship_to_phone_number %>
  </div>
  <!-- <div class="field"> -->
    <%#= f.label :status %>
    <%#= f.text_field :status %>
  <!-- </div> -->
  <!-- <div class="field"> -->
    <%#= f.label :customer_ip %>
    <%#= f.text_field :customer_ip %>
  <!-- </div> -->
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Paypal付款去" %>
  </div>

<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1> <span><%= link_to "Home", products_path  %></span>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Ship to address</th>
      <th>Phone number</th>
      <th>Ship to name</th>
      <th>Ship to phone number</th>
      <th>Status</th>
      <th>Customer ip</th>
      <th>Email</th>
      <th>Total</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.ship_to_address %></td>
        <td><%= order.phone_number %></td>
        <td><%= order.ship_to_name %></td>
        <td><%= order.ship_to_phone_number %></td>
        <td>
          <%= form_for order do |f| %>
            <%= f.select :status, Order::STATUS %>
          <% end %>
        </td>
        <td><%= order.customer_ip %></td>
        <td><%= order.email %></td>
        <td><%= number_to_currency(order.total) %> </td>
        <td><%= time_ago_in_words(order.created_at) %> </td>

        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>訂單資料</h1>

<%= render 'cart/cart' %>


<%= render 'form' %>

<%= link_to 'Back', orders_path %>
<hr>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Ship to address:</strong>
  <%= @order.ship_to_address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @order.phone_number %>
</p>

<p>
  <strong>Ship to name:</strong>
  <%= @order.ship_to_name %>
</p>

<p>
  <strong>Ship to phone number:</strong>
  <%= @order.ship_to_phone_number %>
</p>

<p>

  <%= @order.status %>
</p>

<p>
  <strong>Customer ip:</strong>
  <%= @order.customer_ip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

<hr>
<h2>訂購商品清單</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
    </tr>
  </thead>
<%= @order.order_items.each do |item| %>
  <tr>
    <td><%= item.product.name %></td>
    <td><%= item.product.price %></td>
    <td><%= item.quantity %></td>
  </tr>
<% end %>
</table>

<h4>Total amount :<%= @order.total %> </h4>